#pragma once

const int TOP_TILESIZE = 32;

struct tagImgSet {
	image* img;
	POINT pos;
	RECT rc;
	int frameX;
	int frameY;
	int attribute;
	string imgKeyValue;

};

enum E_TILETYPE_STAGE {
	TILETYPE_CASTLE,
	TILETYPE_EARTH,
	TILETYPE_FIRE,
	TILETYPE_FOREST,


};


enum E_TILE_ATR {
	TILE_NONE,
	TILE_FLOOR,
	TILE_WALL,
	TILE_HOLE,

};

enum E_OBJ_ATR {
	OBJ_NONE,
	OBJ_FURNITURE1,
	OBJ_FURNITURE2,
	OBJ_FURNITURE3,
	OBJ_FURNITURE4,
	OBJ_FURNITURE5,
	OBJ_FURNITURE6,
	OBJ_FURNITURE7,
	OBJ_FURNITURE8,
	OBJ_FURNITURE9,
	OBJ_FURNITURE10,
	OBJ_FURNITURE11,
	OBJ_FURNITURE12,
	OBJ_FURNITURE13,
	OBJ_FURNITURE14,
	OBJ_FURNITURE15,
	OBJ_FURNITURE16,
	OBJ_FURNITURE17,
	OBJ_FURNITURE18,
	OBJ_FURNITURE19,
	OBJ_FURNITURE20,
	OBJ_FURNITURE21,
	OBJ_FURNITURE22,
	OBJ_FURNITURE23,
	OBJ_FURNITURE24,
	OBJ_FURNITURE25,
	OBJ_FURNITURE26,
	OBJ_FURNITURE27,
	OBJ_FURNITURE28,
	OBJ_FURNITURE29,
	OBJ_FURNITURE30,
	OBJ_FURNITURE31,
	OBJ_FURNITURE32,
	OBJ_FURNITURE33,
	OBJ_FURNITURE34,
	OBJ_FURNITURE35,
	OBJ_FURNITURE36,
	OBJ_FURNITURE37,
	OBJ_FURNITURE38,
	OBJ_FURNITURE39,
	OBJ_FURNITURE40,
	OBJ_FURNITURE41,
	OBJ_FURNITURE42,
	OBJ_FURNITURE43,
	OBJ_FURNITURE44,
	OBJ_FURNITURE45,
	OBJ_FURNITURE46,
	OBJ_FURNITURE47,
	OBJ_FURNITURE48,
	OBJ_FURNITURE49,
	OBJ_FURNITURE50,
	OBJ_FURNITURE51,
	OBJ_FURNITURE52,
	OBJ_FURNITURE53,
	OBJ_FURNITURE54,
	OBJ_FURNITURE55,
	OBJ_FURNITURE56,
	OBJ_FURNITURE57,
	OBJ_FURNITURE58,
	OBJ_FURNITURE59,
	OBJ_FURNITURE60,
	OBJ_FURNITURE61,
	OBJ_FURNITURE62,
	OBJ_FURNITURE63,
	OBJ_FURNITURE64,
	OBJ_FURNITURE65,
	OBJ_FURNITURE66,
	OBJ_FURNITURE67,
	OBJ_FURNITURE68,
	OBJ_FURNITURE69,
	OBJ_FURNITURE70,
	OBJ_FURNITURE71,
	OBJ_FURNITURE72,
	OBJ_FURNITURE73,
	OBJ_FURNITURE74,
	OBJ_FURNITURE75,
	OBJ_FURNITURE76,
	OBJ_FURNITURE77,
	OBJ_FURNITURE78,
	OBJ_FURNITURE79,
	OBJ_FURNITURE80,
	OBJ_FURNITURE81,
	OBJ_FURNITURE82,
	OBJ_FURNITURE83,
	OBJ_FURNITURE84,
	OBJ_FURNITURE85,
	OBJ_FURNITURE86,
	OBJ_FURNITURE87,
	OBJ_FURNITURE88,
	OBJ_FURNITURE89,


	OBJ_TREE1,
	OBJ_TREE2,
	OBJ_TREE3,
	OBJ_TREE4,
	OBJ_TREEROOT1,
	OBJ_TREEROOT2,
	OBJ_TREEROOT3,
	OBJ_TREEROOT4,


	OBJ_TRAP1,
	OBJ_TRAP2,
	OBJ_TRAP3,
	OBJ_TRAP4,
	OBJ_TRAP5,
	OBJ_TRAP6,
	OBJ_TRAP7,
	OBJ_TRAP8,
	OBJ_TRAP9,
	OBJ_TRAP10,
	

	OBJ_BREAKABLE,
	OBJ_UNBREAKABLE,
	OBJ_CANDLE,
	OBJ_NEEDLE,
	OBJ_STARTPOINT,


	OBJ_PLAYER_START,

	//=======================À¯´Öµé
	UNIT_GHOUL,
	UNIT_KNIGHT,
	UNIT_LANCER,
	UNIT_ARCHER,

	UNIT_BOSS_FIRE,
	UNIT_BOSS_ICE,
	UNIT_BOSS_EARTH,


};